version: "3.7"
services:
  web:
    build: .
    command: sh -c "python /DjReact/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/DjReact
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
